### ISSUE TITLE
Pelican Themes site down

### ISSUE THREAD

**Issue by bmbufalo** [getpelican/pelican-themes#750] opened 2023-05-29 01:32 UTC
The site shows this when browsing:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
'heroku logs --tail'

![image](https://github.com/getpelican/pelican-themes/assets/15007937/355236b1-d474-4ca1-bbdf-e26d8b679330)

http://www.pelicanthemes.com/

**Comment by justinmayer** [comment] 2023-05-29 07:14
Duplicate of #731. The intention is appreciated, but please check existing issues first. Thanks!

**Closed by justinmayer** 2023-05-29 07:14 UTC
